/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group9.MotorPH_Frames;

import com.group9.domain.Class_Emp;
import com.group9.domain.Class_EmployeeDetails;
import com.group9.services.DatabaseConnectionManager;
import com.group9.services.MotorPHDatabaseConnection;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author brianjancarlos
 */
public class EmployeePortal extends javax.swing.JFrame {

    ResultSet rs = null;

    /**
     * Creates new form EmployeePortal
     */
    public EmployeePortal() {
        initComponents();
        String sql = "SELECT * FROM employee_details WHERE (employee_id = ?)";
        try {
            Connection conn = DatabaseConnectionManager.getConnection();
            lbl_emp.setText(String.valueOf(Class_Emp.empid));
            PreparedStatement pstmt = conn.prepareStatement(sql);
            //Get EmployeeID from Login screen
            pstmt.setInt(1, Integer.parseInt(lbl_emp.getText()));
            rs = pstmt.executeQuery();
            while (rs.next()) {
                Class_EmployeeDetails employee = new Class_EmployeeDetails(rs.getString(1), rs.getString(2),rs.getString(3),
                        rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),
                        rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12), rs.getString(13));
//                String fname = employee.getFirstName();
//                String lname = employee.getLastName();
                lbl_firstName.setText(employee.getFirstName() + " ");
                lbl_lastName.setText(employee.getLastName());
                lbl_birthdate.setText(employee.getBirthday());
                lbl_phoneNum.setText(employee.getPhone());
                lbl_role_designation.setText(employee.getPosition());
                lbl_supervisor.setText(employee.getImmediateSupervisor());
                

/* Code below is implementation option 2. Still figuring out which is better
//            String employeeQuery = "SELECT * FROM public.employee_details WHERE employee_id=?";
//            try (PreparedStatement employeePst = conn.prepareStatement(employeeQuery)) {
//                 employeePst.setInt(1, Integer.parseInt(lbl_emp.getText()));
//
//                try (ResultSet employeeRs = employeePst.executeQuery()) {
//                    if (employeeRs.next()) {
//                        //txt_employee_id.setText(employeeRs.getString("employee_id"));
//                        String fname = employeeRs.getString("last_name");
//                        String lname = employeeRs.getString("first_name");
//                        lbl_firstName_and_lastName.setText(fname + ", " + lname);
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Employee not found");
//                        return; // Exit the method if employee not found
//                    }
//                } */
                rs.close(); // Comment out this line if using Option 2
                conn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeePortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_timeIn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_emp = new javax.swing.JLabel();
        lbl_birthday = new javax.swing.JLabel();
        lbl_supervisor = new javax.swing.JLabel();
        lbl_name1 = new javax.swing.JLabel();
        lbl_immediateSupervisor = new javax.swing.JLabel();
        lbl_birthdate = new javax.swing.JLabel();
        lbl_firstName = new javax.swing.JLabel();
        lbl_employeeId = new javax.swing.JLabel();
        lbl_phoneNum = new javax.swing.JLabel();
        lbl_position = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_role_designation = new javax.swing.JLabel();
        lbl_lastName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_timeIn.setText("Time-In");
        btn_timeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timeInActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Profile"));

        lbl_emp.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_emp.setText("Employee_num");

        lbl_birthday.setText("Birthday");

        lbl_supervisor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_supervisor.setText("Supervisor");

        lbl_name1.setText("Phone Number");

        lbl_immediateSupervisor.setText("Immediate Supervisor");

        lbl_birthdate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_birthdate.setText("Birthdate");

        lbl_firstName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_firstName.setText("FirstName");

        lbl_employeeId.setText("Employee ID");

        lbl_phoneNum.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_phoneNum.setText("Phone");

        lbl_position.setText("Position");

        lbl_name.setText("Name");

        lbl_role_designation.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_role_designation.setText("Position");

        lbl_lastName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbl_lastName.setText(", Last Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name)
                            .addComponent(lbl_employeeId)
                            .addComponent(lbl_emp)
                            .addComponent(lbl_birthday)
                            .addComponent(lbl_birthdate))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_firstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(lbl_lastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_supervisor)
                    .addComponent(lbl_position)
                    .addComponent(lbl_phoneNum)
                    .addComponent(lbl_name1)
                    .addComponent(lbl_role_designation)
                    .addComponent(lbl_immediateSupervisor))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(lbl_name1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_firstName)
                    .addComponent(lbl_phoneNum)
                    .addComponent(lbl_lastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_employeeId)
                    .addComponent(lbl_position))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_emp)
                    .addComponent(lbl_role_designation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_birthday)
                    .addComponent(lbl_immediateSupervisor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_birthdate)
                    .addComponent(lbl_supervisor))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_timeIn)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_timeIn)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timeInActionPerformed
        
        Date loginDate = Date.valueOf(LocalDate.now());
        Time timeIn = Time.valueOf(LocalTime.now());
        Time timeOut = null; // Set the timeout value as needed

        // Insert values into the attendance_record table
        try {
            Connection connection = DatabaseConnectionManager.getConnection();
            String query = "INSERT INTO attendance_record (employee_id, last_name, first_name, login_date, timein, timeout) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setInt(1, Class_Emp.empid);
            statement.setString(2, lbl_lastName.getText());
            statement.setString(3, lbl_firstName.getText());
            statement.setDate(4, loginDate);
            statement.setTime(5, timeIn);
            statement.setTime(6, timeOut);
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Attendance recorded successfully.");
        } catch (SQLException ex) {
            Logger.getLogger(EmployeePortal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to record attendance.");
        }
    }//GEN-LAST:event_btn_timeInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_timeIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_birthdate;
    private javax.swing.JLabel lbl_birthday;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_employeeId;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_immediateSupervisor;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_phoneNum;
    private javax.swing.JLabel lbl_position;
    private javax.swing.JLabel lbl_role_designation;
    private javax.swing.JLabel lbl_supervisor;
    // End of variables declaration//GEN-END:variables
}
