/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group9.MotorPH_Frames;

import com.group9.domain.Class_Emp;
import com.group9.services.DatabaseConnectionManager;
import com.group9.services.WindowPositioner;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author nativ
 */
public class MainMenuPortal extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuPortal
     */
    public MainMenuPortal()   {
        initComponents();
        
        //Jframe Color
        setBackground(new java.awt.Color(255, 214, 196));
         getContentPane().setBackground(new java.awt.Color(255, 214, 196));
        // Establish a connection to the database MotorPH.services
         
            //Displays Current date in form
            currentDate();
            
            
        /*
        This line takes the employee ID from a specific place in the program, 
        turns it into a text, and then shows it on the screen in a specific area.
         */
        lbl_emp.setText(String.valueOf(Class_Emp.empid));

        WindowPositioner.centerWindow(this);
    }
    
    public final void currentDate() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        lbl_date.setText((month + 1) + "/" + day + "/" + year);

        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        lbl_time.setText(hour + ":" + (minute) + ":" + second);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_logout = new javax.swing.JButton();
        lbl_loggedin_user = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        btn_payslip = new javax.swing.JButton();
        btn_payroll = new javax.swing.JButton();
        btn_employee = new javax.swing.JButton();
        btn_attendance = new javax.swing.JButton();
        btn_timein_out = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnubar_loginPortal = new javax.swing.JMenuBar();
        mnu_file = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setBackground(new java.awt.Color(255, 145, 0));
        btn_logout.setForeground(new java.awt.Color(14, 49, 113));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 90, 30));

        lbl_loggedin_user.setText("Logged in as:");
        getContentPane().add(lbl_loggedin_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        lbl_emp.setText("employee id");
        getContentPane().add(lbl_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        btn_payslip.setBackground(new java.awt.Color(14, 49, 113));
        btn_payslip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_payslip.setForeground(new java.awt.Color(255, 255, 255));
        btn_payslip.setText("Payslip");
        btn_payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payslipActionPerformed(evt);
            }
        });
        getContentPane().add(btn_payslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 153, 43));

        btn_payroll.setBackground(new java.awt.Color(14, 49, 113));
        btn_payroll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_payroll.setForeground(new java.awt.Color(255, 255, 255));
        btn_payroll.setText("Payroll");
        btn_payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payrollActionPerformed(evt);
            }
        });
        getContentPane().add(btn_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 153, 43));

        btn_employee.setBackground(new java.awt.Color(14, 49, 113));
        btn_employee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_employee.setForeground(new java.awt.Color(255, 255, 255));
        btn_employee.setText("Employee  ");
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 153, 43));

        btn_attendance.setBackground(new java.awt.Color(14, 49, 113));
        btn_attendance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_attendance.setForeground(new java.awt.Color(255, 255, 255));
        btn_attendance.setText("Attendance");
        btn_attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attendanceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 153, 43));

        btn_timein_out.setBackground(new java.awt.Color(14, 49, 113));
        btn_timein_out.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timein_out.setForeground(new java.awt.Color(255, 255, 255));
        btn_timein_out.setText("Time-in/out");
        btn_timein_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timein_outActionPerformed(evt);
            }
        });
        getContentPane().add(btn_timein_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 153, 43));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_image/aesthetics pNG.png"))); // NOI18N
        jLabel1.setMixingCutoutShape(null);
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 910, 390));

        mnubar_loginPortal.setBackground(new java.awt.Color(14, 49, 113));
        mnubar_loginPortal.setForeground(new java.awt.Color(14, 49, 113));

        mnu_file.setForeground(new java.awt.Color(14, 49, 113));
        mnu_file.setText("MotorPH");
        mnu_file.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        mnu_file.setMaximumSize(new java.awt.Dimension(60, 32767));
        mnubar_loginPortal.add(mnu_file);

        jMenu2.setForeground(new java.awt.Color(14, 49, 113));
        jMenu2.setText("About");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        mnubar_loginPortal.add(jMenu2);

        lbl_date.setForeground(new java.awt.Color(14, 49, 113));
        lbl_date.setText("Date");
        lbl_date.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        mnubar_loginPortal.add(lbl_date);

        lbl_time.setForeground(new java.awt.Color(14, 49, 113));
        lbl_time.setText("Time");
        lbl_time.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        mnubar_loginPortal.add(lbl_time);

        setJMenuBar(mnubar_loginPortal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // Logout button

        login_portal login_ui = new login_portal();
        login_ui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payrollActionPerformed
        // payroll_old

        payroll x = new payroll();
        x.setVisible(true);

    }//GEN-LAST:event_btn_payrollActionPerformed

    private void btn_attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attendanceActionPerformed
        // Attendance

        Attendance_Record x = new Attendance_Record();
        x.setVisible(true);

    }//GEN-LAST:event_btn_attendanceActionPerformed

    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employeeActionPerformed
        // add employee
        //Show EmplooyeeDetails_view
        Employee_Details_HRView employeeDetailsHRView = new Employee_Details_HRView();
        employeeDetailsHRView.setVisible(true);

//        addEmployee x = new addEmployee();
//        x.setVisible(true);

    }//GEN-LAST:event_btn_employeeActionPerformed

    private void btn_timein_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timein_outActionPerformed
        // Administrator

        EmployeePortal x = new EmployeePortal();
        x.setVisible(true);


    }//GEN-LAST:event_btn_timein_outActionPerformed

    private void btn_payslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payslipActionPerformed
        Payslip_employee x = new Payslip_employee();
        x.setVisible(true);
    }//GEN-LAST:event_btn_payslipActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // About
        
         about x = new about();
        x.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attendance;
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_payroll;
    private javax.swing.JButton btn_payslip;
    private javax.swing.JButton btn_timein_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_loggedin_user;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JMenu mnu_file;
    private javax.swing.JMenuBar mnubar_loginPortal;
    // End of variables declaration//GEN-END:variables
}
